name: dynamic_tabs_example
description: Demonstrates how to use the dynamic_tabs plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  dynamic_tabs:
    path: ..
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
